In [1]:
import numpy as np
import random
import os
import shutil

In [ ]:
real_indices

NameError: ignored

In [ ]:
new_file = ''
selected_atoms = []
initial_atom_

[15, 3]

In [ ]:
    global a
    def place_clustered():
        new_file = ''
        global selected_atoms
        selected_atoms = []
        initial_atom_index = random.sample(range(len(a.orig_atom_coords)), k=1)       #index WRT self.orig_atom_coords
        selected_atoms.append(initial_atom_index[0])

        for c in [1,2,3]:
            global remaining_arr
            
            remaining_arr = np.delete(a.orig_atom_coords, selected_atoms, axis=0)
            global distances_arr
            distances_arr = np.zeros((remaining_arr.shape[0],len(selected_atoms)))

            print(remaining_arr)
            for i, atom in enumerate(selected_atoms):
                global atom_coords
                atom_coords = a.orig_atom_coords[atom, 1:]
                distances_arr[:,i] = (np.sum((remaining_arr[:, 1:] - atom_coords)**2
                                        , axis=1) ** 0.5)
            
            global new_atom_index
            new_atom_index = np.sum(distances_arr, axis=1).argmin()           #index WRT remaining_arr
            idx = np.where(a.orig_atom_coords[:,0] == remaining_arr[new_atom_index, 0])     #index WRT self.orig_atom_coords
            selected_atoms.append(int(idx[0]))

        global real_indices
        real_indices = []
        for atom in selected_atoms:
            real_indices.append(a.orig_atom_coords[atom, 0])           #index WRT lines
        
        
        for i, line in enumerate(a.lines):
            if i in selected_atoms:
                line = line.replace(a.orig_atom, a.dopant)
                new_file += line
            else:
                new_file += line

        with open('dopant_analysis/' + str(a.percentage) + '_clustered.txt', 'a') as f:
            f.write(new_file)

    place_clustered()

In [ ]:
atom_coords

array([3.78742, 9.83656, 4.08324], dtype=object)

In [ ]:
a1 = a.orig_atom_coords[56]
a1

array([106, 7.57758, 6.55844, 1.44456], dtype=object)

In [ ]:
a2 = a.orig_atom_coords[50]
a2

array([100, 6.62959, 8.19773, 4.08315], dtype=object)

In [ ]:
np.sum((a1[1:]-a2[1:])**2))

3.2479270325547644

In [ ]:
selected_atoms

[56, 50, 62, 58]

In [ ]:
real_indices

[106, 100, 112, 108]

array([5, 0.94528, 4.91737, 9.36022], dtype=object)

In [ ]:
remaining_arr[3]

array([5, 0.94528, 4.91737, 9.36022], dtype=object)

In [ ]:
np.sum((remaining_arr[:, 1:] - atom_coords)**2, axis=1)**0.5

array([4.615086360632919, 4.6149605808609016, 3.247973644874601,
       3.2479270325547644, 5.663861732793271, 5.663749926841756,
       3.2480519070359697, 3.2480031661314617, 6.21290214976061,
       3.279000000975907, 6.214123952336323, 3.281455502060023,
       6.213844199640027, 3.2807846047858735, 5.277060000009476,
       4.615662714811386, 4.615719879162946, 5.661220374106629,
       5.661331189252223, 7.321005369879194, 7.321034202255854,
       7.318633358571805, 7.318727093750661, 6.212766248628706,
       3.279000000975908, 7.752969891686669, 5.680027584228795,
       7.753887538196566, 5.681210126355124, 8.417424642377265,
       6.558000001951815, 10.36244051943846, 10.362297928804209,
       7.319572887225046, 7.3194418845564995, 11.82032380729902,
       11.820194339121503, 8.668115678704341, 8.667993919898652,
       10.156340850291507, 8.677623703952598, 7.753195491808523,
       5.680056257661537, 11.167921664490667, 9.842376135334394,
       8.420436659954161, 6.561

In [ ]:
distances_arr

array([[ 4.61508636],
       [ 4.61496058],
       [ 3.24797364],
       [ 3.24792703],
       [ 5.66386173],
       [ 5.66374993],
       [ 3.24805191],
       [ 3.24800317],
       [ 6.21290215],
       [ 3.279     ],
       [ 6.21412395],
       [ 3.2814555 ],
       [ 6.2138442 ],
       [ 3.2807846 ],
       [ 5.27706   ],
       [ 4.61566271],
       [ 4.61571988],
       [ 5.66122037],
       [ 5.66133119],
       [ 7.32100537],
       [ 7.3210342 ],
       [ 7.31863336],
       [ 7.31872709],
       [ 6.21276625],
       [ 3.279     ],
       [ 7.75296989],
       [ 5.68002758],
       [ 7.75388754],
       [ 5.68121013],
       [ 8.41742464],
       [ 6.558     ],
       [10.36244052],
       [10.36229793],
       [ 7.31957289],
       [ 7.31944188],
       [11.82032381],
       [11.82019434],
       [ 8.66811568],
       [ 8.66799392],
       [10.15634085],
       [ 8.6776237 ],
       [ 7.75319549],
       [ 5.68005626],
       [11.16792166],
       [ 9.84237614],
       [ 8

In [ ]:
np.where(a.orig_atom_coords[:,0] == remaining_arr[new_atom_index, 0]) 

(array([29]),)

In [ ]:
a.orig_atom_coords[29]

array([47, 4.73541, 11.47627, 6.72179], dtype=object)

In [ ]:
new_atom_index

28

In [ ]:
remaining_arr[28]

array([47, 4.73541, 11.47627, 6.72179], dtype=object)

In [ ]:
selected_atoms

[22, 29]

In [ ]:
real_indices

[109, 34]

In [ ]:
(np.sum((remaining_arr[:, 1:] - atom_coords)**2
                                        , axis=1) ** 0.5).reshape(-1, 1)

array([[33.90089360165203],
       [38.08375629959108],
       [45.77699545610404],
       ...,
       [22.526741393742135],
       [33.31119207790832],
       [45.34176738963147]], dtype=object)

In [ ]:
atom_coords.shape

(3,)

In [ ]:
a = Place_Dopants('a', 'xmolout', 'Zn', 'Mg', 25)

In [ ]:
a.file_handler()

In [ ]:
a.orig_atom_coords

array([[610, -7.58077, -9.83610002, 3.56429695],
       [611, -7.58077, 3.27989998, 3.56461743],
       [612, -7.58077, 16.39589998, 3.56493791],
       ...,
       [9695, 29.37138, 1.64108002, 19.39479442],
       [9696, 29.37138, 14.75708001, 19.3951149],
       [9697, 29.37138, 27.87308001, 19.39543538]], dtype=object)

In [ ]:
a.place_clustered()

In [ ]:
class Place_Dopants():

    def __init__(self, method, file_name, orig_atom, dopant, percentage):
        self.method = method
        self.file_name = file_name
        self.orig_atom = orig_atom
        self.dopant = dopant
        self.num_orig = 0
        self.orig_atom_coords = []
        self.percentage = percentage




    def file_handler(self):
        if not os.path.exists('dopand_analysis'):
            os.mkdir('dopant_analysis')

        new_fname = 'dopant_analysis/' + self.file_name.split('.')[0] + '.txt'
        shutil.copy(self.file_name, new_fname)
        
        with open(new_fname, 'r') as f:
            self.lines = f.readlines()
        
        self.num_atoms = int(self.lines[0].strip())
        
        for i, line in enumerate(self.lines):
            if line.startswith(self.orig_atom):
                self.num_orig += 1
                self.orig_atom_coords.append((int(i), float(line.split()[1]),
                                              float(line.split()[2]),
                                              float(line.split()[3])))
        
        self.count = int(self.percentage * self.num_orig / 100)
        self.orig_atom_coords = np.array(self.orig_atom_coords, dtype=object)




    def place_random(self):
        new_file = ''
        sample_list = random.sample(self.orig_atom_coords[:,0], k=self.count)

        for i, line in enumerate(self.lines):
            if i in sample_list:
                line = line.replace(self.orig_atom, self.dopant)
                new_file += line
            else:
                new_file += line

        with open('dopant_analysis/' + str(self.percentage) + '_random.txt', 'a') as f:
            f.write(new_file)




    def place_clustered(self):
        new_file = ''
        selected_atoms = []
        initial_atom_index = random.sample(range(len(self.orig_atom_coords)), k=1)       #index WRT self.orig_atom_coords
        selected_atoms.append(initial_atom_index[0])

        for c in range(self.count-1):
            remaining_arr = np.delete(self.orig_atom_coords, selected_atoms, axis=0)
            distances_arr = np.zeros((remaining_arr.shape[0],len(selected_atoms)))
            for i, atom in enumerate(selected_atoms):
                atom_coords = self.orig_atom_coords[atom, 1:]
                distances_arr[:,i] = (np.sum((remaining_arr[:, 1:] - atom_coords)**2
                                        , axis=1) ** 0.5)
            
            new_atom_index = np.sum(distances_arr, axis=1).argmin()          #index WRT remaining_arr
            idx = np.where(self.orig_atom_coords[:,0] == remaining_arr[new_atom_index, 0])     #index WRT self.orig_atom_coords
            selected_atoms.append(int(idx[0]))

        real_indices = []
        for atom in selected_atoms:
            real_indices.append(self.orig_atom_coords[atom, 0])           #index WRT lines
        
        
        for i, line in enumerate(self.lines):
            if i in selected_atoms:
                line = line.replace(self.orig_atom, self.dopant)
                new_file += line
            else:
                new_file += line

        with open('dopant_analysis/' + str(self.percentage) + '_clustered.txt', 'a') as f:
            f.write(new_file)




    def place_dispersed(self):
        new_file = ''
        selected_atoms = []
        initial_atom_index = random.sample(range(len(self.orig_atom_coords)), k=1)
        selected_atoms.append(initial_atom_index[0])

        for c in range(self.count-1):
            remaining_arr = np.delete(self.orig_atom_coords, selected_atoms, axis=0)
            distances_arr = np.zeros(remaining_arr.shape[0],len(selected_atoms))
            for i, atom in enumerate(selected_atoms):
                atom_coords = self.orig_atom_coords[atom, 1:]
                distances_arr[:,i] = (np.sum((remaining_arr[:, 1:] - atom_coords)**2
                                        , axis=1) ** 0.5)
            
            new_atom_index = distances_arr.min(axis=1).argmax()
            selected_atoms.append(remaining_arr[new_atom_index, 1])

        for i, line in enumerate(self.lines):
            if i in selected_atoms:
                line = line.replace(self.orig_atom, self.dopant)
                self.new_file += line
            else:
                self.new_file += line

        with open('dopant_analysis/' + str(self.percentage) + '_dispersed.txt', 'a') as new_file:
            new_file.write(new_file)

In [ ]:
import numpy as np
a = np.array(([0,1,2], [1,2,3], [3,4,5]))
b = np.delete(a, [0,1], axis=0)

In [ ]:
(np.sum((a - [1,1,1])**2, axis=1)**0.5).reshape(-1,1)

array([[1.41421356],
       [2.23606798],
       [5.38516481]])

In [ ]:
a[:,1:] - [1,1]

array([[0, 1],
       [1, 2],
       [3, 4]])

In [ ]:
a

array([[0, 1, 2],
       [1, 2, 3],
       [3, 4, 5]])

In [ ]:
a[np.where(a[:,0]==1)[0]]

array([[1, 2, 3]])

In [ ]:
a = ['a 1 0 0', 'b 0 1 0', 'c 0 0 1']